/**
 * Copyright © 2026 Pangolin
 *
 * SPDX-License-Identifier: Apache-2.0
 */

package com.pangolin.validation;

/**
 * Centralised ID format validation.
 * Previously the UUID regex was duplicated across three controllers.
 */
public final class IdValidator {

    /** Standard UUID format used by Flamenco for all job and task IDs. */
    private static final String FLAMENCO_UUID_REGEX =
            "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}";

    /** 16-character hex ID generated by Pangolin on job submission. */
    private static final String PANGOLIN_JOB_ID_REGEX = "[a-f0-9]{16}";

    private IdValidator() {}

    public static boolean isValidFlamencoId(String id) {
        return id != null && id.matches(FLAMENCO_UUID_REGEX);
    }

    public static boolean isValidPangolinId(String id) {
        return id != null && id.matches(PANGOLIN_JOB_ID_REGEX);
    }
}